name: job_board_flutter_app
description: A job board application for job seekers and employers.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  animations: ^2.0.7

  # Firebase & Backend
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_crashlytics: ^4.3.6
  firebase_app_check: ^0.3.2+6
  http: ^1.2.2
  path: ^1.8.3
  mime: ^1.0.4
  supabase_flutter: ^2.9.1
  sign_in_with_apple: ^6.1.0


  # State Management & Utils
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.2.6
  timeago: ^3.6.0
  fluttertoast: ^8.2.4

  # File Uploads & Viewing
  file_picker: ^10.1.9
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Optional font setup (you can uncomment and use it if you have font files)
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/Poppins-Bold.ttf
#          weight: 700
